package com.lxy.learn.mapper.postgres.mybatis;

import com.lxy.learn.model.entity.postgres.SysUserEntity;

public interface SysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Thu Mar 13 15:45:16 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Thu Mar 13 15:45:16 CST 2025
     */
    int insert(SysUserEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Thu Mar 13 15:45:16 CST 2025
     */
    int insertSelective(SysUserEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Thu Mar 13 15:45:16 CST 2025
     */
    SysUserEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Thu Mar 13 15:45:16 CST 2025
     */
    int updateByPrimaryKeySelective(SysUserEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbg.generated Thu Mar 13 15:45:16 CST 2025
     */
    int updateByPrimaryKey(SysUserEntity row);
}